name: metrics
on:
  # Run every day at 00:30 and 12:30 America/Sao_Paulo
  schedule: [{ cron: "30 3,15 * * *" }]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: felipecrs/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          debug: yes

          user: felipecrs
          template: classic
          config_gemoji: yes
          config_timezone: America/Sao_Paulo
          use_prebuilt_image: no # using my fork instead
          notice_releases: no
          retries: 3
          retries_delay: 300
          config_padding: 0, 10 + 8%
          optimize: css, xml, svg
          experimental_features: --optimize-svg

          base: header, activity, community, repositories # removed metadata
          base_indepth: yes
          repositories: 500
          repositories_batch: 50
          users_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot], actions-user, action@github.com, renovate[bot] # default list plus renovate

          plugin_traffic: yes

          plugin_lines: yes
          plugin_lines_delay: 30

          plugin_repositories: yes
          plugin_repositories_featured: volume-locker, openwrt-dns-watchdog

          plugin_followup: yes
          plugin_followup_sections: user

          plugin_languages: yes
          plugin_languages_ignored: c, c++, c#, java, dockerfile
          plugin_languages_aliases: renderscript:Rust
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_languages_sections: most-used, recently-used

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_filter: stars:>500
          plugin_notable_types: commit, pull_request
          plugin_notable_skipped: |
            winfsp/sshfs-win
            keesschollaart81/vscode-home-assistant
            blakeblackshear/frigate-hass-integration
            xZetsubou/hass-localtuya
 
          plugin_stargazers: yes

          plugin_reactions: yes
          plugin_reactions_details: count
