name: Metrics
on:
  # Schedule updates (00:30 && 12:30 UTC daily)
  schedule: [{ cron: "30 0,12 * * *" }]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          debug: yes

          user: felipecrs
          template: classic
          config_gemoji: yes
          config_timezone: America/Sao_Paulo
          use_prebuilt_image: yes
          notice_releases: no
          retries: 3
          retries_delay: 300
          optimize: css, xml, svg
          experimental_features: --optimize-svg

          base_indepth: yes
          repositories: 300
          repositories_batch: 50
          users_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot], actions-user, action@github.com, renovate[bot] # default list plus renovate

          plugin_traffic: yes

          plugin_repositories: yes
          plugin_repositories_featured: volume-locker, openwrt-dns-watchdog

          plugin_followup: yes
          plugin_followup_sections: user

          plugin_languages: yes
          plugin_languages_ignored: c, c++, c#, java, dockerfile
          plugin_languages_aliases: renderscript:Rust
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_languages_sections: most-used, recently-used

          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_types: commit, pull_request
 
          plugin_reactions: yes
          plugin_reactions_details: count
